package com.coms.warehouse.beans.manage;

import java.util.Date;

public class TStoragePartially {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_id
     *
     * @mbggenerated
     */
    private Integer mateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_name
     *
     * @mbggenerated
     */
    private String mateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_size
     *
     * @mbggenerated
     */
    private String mateSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_count
     *
     * @mbggenerated
     */
    private Float mateCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_price
     *
     * @mbggenerated
     */
    private Float matePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_totle
     *
     * @mbggenerated
     */
    private Float mateTotle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.mate_batch_code
     *
     * @mbggenerated
     */
    private String mateBatchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.Product_status
     *
     * @mbggenerated
     */
    private Byte productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.out_time
     *
     * @mbggenerated
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.part_user_id
     *
     * @mbggenerated
     */
    private Integer partUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.op_person
     *
     * @mbggenerated
     */
    private Integer opPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.modf_time
     *
     * @mbggenerated
     */
    private Date modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially.rmk
     *
     * @mbggenerated
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    public TStoragePartially(Integer mateId, String mateName, String alias, String mateSize, Float mateCount, Float matePrice, Float mateTotle, String mateBatchCode, Byte productStatus, Date outTime, Integer partUserId, Integer opPerson, Date crtTime, Date modfTime, String rmk) {
        this.mateId = mateId;
        this.mateName = mateName;
        this.alias = alias;
        this.mateSize = mateSize;
        this.mateCount = mateCount;
        this.matePrice = matePrice;
        this.mateTotle = mateTotle;
        this.mateBatchCode = mateBatchCode;
        this.productStatus = productStatus;
        this.outTime = outTime;
        this.partUserId = partUserId;
        this.opPerson = opPerson;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_id
     *
     * @return the value of t_storage_partially.mate_id
     *
     * @mbggenerated
     */
    public Integer getMateId() {
        return mateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_name
     *
     * @return the value of t_storage_partially.mate_name
     *
     * @mbggenerated
     */
    public String getMateName() {
        return mateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.alias
     *
     * @return the value of t_storage_partially.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_size
     *
     * @return the value of t_storage_partially.mate_size
     *
     * @mbggenerated
     */
    public String getMateSize() {
        return mateSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_count
     *
     * @return the value of t_storage_partially.mate_count
     *
     * @mbggenerated
     */
    public Float getMateCount() {
        return mateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_price
     *
     * @return the value of t_storage_partially.mate_price
     *
     * @mbggenerated
     */
    public Float getMatePrice() {
        return matePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_totle
     *
     * @return the value of t_storage_partially.mate_totle
     *
     * @mbggenerated
     */
    public Float getMateTotle() {
        return mateTotle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.mate_batch_code
     *
     * @return the value of t_storage_partially.mate_batch_code
     *
     * @mbggenerated
     */
    public String getMateBatchCode() {
        return mateBatchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.Product_status
     *
     * @return the value of t_storage_partially.Product_status
     *
     * @mbggenerated
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.out_time
     *
     * @return the value of t_storage_partially.out_time
     *
     * @mbggenerated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.part_user_id
     *
     * @return the value of t_storage_partially.part_user_id
     *
     * @mbggenerated
     */
    public Integer getPartUserId() {
        return partUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.op_person
     *
     * @return the value of t_storage_partially.op_person
     *
     * @mbggenerated
     */
    public Integer getOpPerson() {
        return opPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.crt_time
     *
     * @return the value of t_storage_partially.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.modf_time
     *
     * @return the value of t_storage_partially.modf_time
     *
     * @mbggenerated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially.rmk
     *
     * @return the value of t_storage_partially.rmk
     *
     * @mbggenerated
     */
    public String getRmk() {
        return rmk;
    }
}