package com.coms.warehouse.beans.manage;

import java.util.Date;

public class TStoragePartiallyProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_id
     *
     * @mbggenerated
     */
    private Integer partId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_name
     *
     * @mbggenerated
     */
    private String partName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_size
     *
     * @mbggenerated
     */
    private String partSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_count
     *
     * @mbggenerated
     */
    private Float partCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_price
     *
     * @mbggenerated
     */
    private Float partPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_totle
     *
     * @mbggenerated
     */
    private Float partTotle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_batch_code
     *
     * @mbggenerated
     */
    private String partBatchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.Product_status
     *
     * @mbggenerated
     */
    private Byte productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.out_time
     *
     * @mbggenerated
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.part_user_id
     *
     * @mbggenerated
     */
    private Integer partUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.op_person
     *
     * @mbggenerated
     */
    private Integer opPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.modf_time
     *
     * @mbggenerated
     */
    private Date modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_partially_product.rmk
     *
     * @mbggenerated
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially_product
     *
     * @mbggenerated
     */
    public TStoragePartiallyProduct(Integer partId, String partName, String alias, String partSize, Float partCount, Float partPrice, Float partTotle, String partBatchCode, Byte productStatus, Date outTime, Integer partUserId, Integer opPerson, Date crtTime, Date modfTime, String rmk) {
        this.partId = partId;
        this.partName = partName;
        this.alias = alias;
        this.partSize = partSize;
        this.partCount = partCount;
        this.partPrice = partPrice;
        this.partTotle = partTotle;
        this.partBatchCode = partBatchCode;
        this.productStatus = productStatus;
        this.outTime = outTime;
        this.partUserId = partUserId;
        this.opPerson = opPerson;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_id
     *
     * @return the value of t_storage_partially_product.part_id
     *
     * @mbggenerated
     */
    public Integer getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_name
     *
     * @return the value of t_storage_partially_product.part_name
     *
     * @mbggenerated
     */
    public String getPartName() {
        return partName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.alias
     *
     * @return the value of t_storage_partially_product.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_size
     *
     * @return the value of t_storage_partially_product.part_size
     *
     * @mbggenerated
     */
    public String getPartSize() {
        return partSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_count
     *
     * @return the value of t_storage_partially_product.part_count
     *
     * @mbggenerated
     */
    public Float getPartCount() {
        return partCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_price
     *
     * @return the value of t_storage_partially_product.part_price
     *
     * @mbggenerated
     */
    public Float getPartPrice() {
        return partPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_totle
     *
     * @return the value of t_storage_partially_product.part_totle
     *
     * @mbggenerated
     */
    public Float getPartTotle() {
        return partTotle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_batch_code
     *
     * @return the value of t_storage_partially_product.part_batch_code
     *
     * @mbggenerated
     */
    public String getPartBatchCode() {
        return partBatchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.Product_status
     *
     * @return the value of t_storage_partially_product.Product_status
     *
     * @mbggenerated
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.out_time
     *
     * @return the value of t_storage_partially_product.out_time
     *
     * @mbggenerated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.part_user_id
     *
     * @return the value of t_storage_partially_product.part_user_id
     *
     * @mbggenerated
     */
    public Integer getPartUserId() {
        return partUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.op_person
     *
     * @return the value of t_storage_partially_product.op_person
     *
     * @mbggenerated
     */
    public Integer getOpPerson() {
        return opPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.crt_time
     *
     * @return the value of t_storage_partially_product.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.modf_time
     *
     * @return the value of t_storage_partially_product.modf_time
     *
     * @mbggenerated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_partially_product.rmk
     *
     * @return the value of t_storage_partially_product.rmk
     *
     * @mbggenerated
     */
    public String getRmk() {
        return rmk;
    }
}