package com.coms.warehouse.beans.basic;

import java.util.Date;

public class TGroupWork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.menu_code
     *
     * @mbggenerated
     */
    private Integer menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.op_person
     *
     * @mbggenerated
     */
    private Integer opPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_work.modf_time
     *
     * @mbggenerated
     */
    private Date modfTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_work
     *
     * @mbggenerated
     */
    public TGroupWork(String groupId, String groupName, Integer menuCode, Integer opPerson, Date crtTime, Date modfTime) {
        this.groupId = groupId;
        this.groupName = groupName;
        this.menuCode = menuCode;
        this.opPerson = opPerson;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.group_id
     *
     * @return the value of t_group_work.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.group_name
     *
     * @return the value of t_group_work.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.menu_code
     *
     * @return the value of t_group_work.menu_code
     *
     * @mbggenerated
     */
    public Integer getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.op_person
     *
     * @return the value of t_group_work.op_person
     *
     * @mbggenerated
     */
    public Integer getOpPerson() {
        return opPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.crt_time
     *
     * @return the value of t_group_work.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_work.modf_time
     *
     * @return the value of t_group_work.modf_time
     *
     * @mbggenerated
     */
    public Date getModfTime() {
        return modfTime;
    }
}