package com.coms.warehouse.beans.basic;

import java.util.Date;

public class TMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_code
     *
     * @mbggenerated
     */
    private Integer menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_src
     *
     * @mbggenerated
     */
    private String menuSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_type
     *
     * @mbggenerated
     */
    private Byte menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.unit_code
     *
     * @mbggenerated
     */
    private Integer unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.op_person
     *
     * @mbggenerated
     */
    private Integer opPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.modf_time
     *
     * @mbggenerated
     */
    private Date modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.rmk
     *
     * @mbggenerated
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated
     */
    public TMenu(Integer menuId, Integer menuCode, String menuName, String menuSrc, Byte menuType, Integer unitCode, Integer opPerson, Date crtTime, Date modfTime, String rmk) {
        this.menuId = menuId;
        this.menuCode = menuCode;
        this.menuName = menuName;
        this.menuSrc = menuSrc;
        this.menuType = menuType;
        this.unitCode = unitCode;
        this.opPerson = opPerson;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_id
     *
     * @return the value of t_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_code
     *
     * @return the value of t_menu.menu_code
     *
     * @mbggenerated
     */
    public Integer getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_name
     *
     * @return the value of t_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_src
     *
     * @return the value of t_menu.menu_src
     *
     * @mbggenerated
     */
    public String getMenuSrc() {
        return menuSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_type
     *
     * @return the value of t_menu.menu_type
     *
     * @mbggenerated
     */
    public Byte getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.unit_code
     *
     * @return the value of t_menu.unit_code
     *
     * @mbggenerated
     */
    public Integer getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.op_person
     *
     * @return the value of t_menu.op_person
     *
     * @mbggenerated
     */
    public Integer getOpPerson() {
        return opPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.crt_time
     *
     * @return the value of t_menu.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.modf_time
     *
     * @return the value of t_menu.modf_time
     *
     * @mbggenerated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.rmk
     *
     * @return the value of t_menu.rmk
     *
     * @mbggenerated
     */
    public String getRmk() {
        return rmk;
    }
}