package com.coms.warehouse.beans.basic;

import java.util.Date;

public class TSysUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.unit_id
     *
     * @mbggenerated
     */
    private Integer unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.unit_name
     *
     * @mbggenerated
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.unit_code
     *
     * @mbggenerated
     */
    private Integer unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.unit_src
     *
     * @mbggenerated
     */
    private String unitSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.modf_time
     *
     * @mbggenerated
     */
    private Date modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.op_person
     *
     * @mbggenerated
     */
    private Integer opPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_unit.rmk
     *
     * @mbggenerated
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_unit
     *
     * @mbggenerated
     */
    public TSysUnit(Integer unitId, String unitName, Integer unitCode, String unitSrc, Date crtTime, Date modfTime, Integer opPerson, String rmk) {
        this.unitId = unitId;
        this.unitName = unitName;
        this.unitCode = unitCode;
        this.unitSrc = unitSrc;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.opPerson = opPerson;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.unit_id
     *
     * @return the value of t_sys_unit.unit_id
     *
     * @mbggenerated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.unit_name
     *
     * @return the value of t_sys_unit.unit_name
     *
     * @mbggenerated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.unit_code
     *
     * @return the value of t_sys_unit.unit_code
     *
     * @mbggenerated
     */
    public Integer getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.unit_src
     *
     * @return the value of t_sys_unit.unit_src
     *
     * @mbggenerated
     */
    public String getUnitSrc() {
        return unitSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.crt_time
     *
     * @return the value of t_sys_unit.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.modf_time
     *
     * @return the value of t_sys_unit.modf_time
     *
     * @mbggenerated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.op_person
     *
     * @return the value of t_sys_unit.op_person
     *
     * @mbggenerated
     */
    public Integer getOpPerson() {
        return opPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_unit.rmk
     *
     * @return the value of t_sys_unit.rmk
     *
     * @mbggenerated
     */
    public String getRmk() {
        return rmk;
    }
}