package com.coms.warehouse.dao.basic;

import com.coms.warehouse.beans.basic.TGroupWork;

public interface TGroupWorkDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_work
     *
     * @mbggenerated
     */
    int insert(TGroupWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_work
     *
     * @mbggenerated
     */
    int insertSelective(TGroupWork record);
}