package com.coms.warehouse.dao.basic;

import com.coms.warehouse.beans.basic.TSysUnit;

public interface TSysUnitDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_unit
     *
     * @mbggenerated
     */
    int insert(TSysUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_unit
     *
     * @mbggenerated
     */
    int insertSelective(TSysUnit record);
}