package com.coms.warehouse.dao.manage;

import com.coms.warehouse.beans.manage.TStorageMaterial;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TStorageMaterialDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_material
     *
     * @mbggenerated
     */
    int insert(TStorageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_material
     *
     * @mbggenerated
     */
    int insertSelective(TStorageMaterial record);
}