package com.coms.warehouse.dao.manage;

import com.coms.warehouse.beans.manage.TStoragePartiallyProduct;

public interface TStoragePartiallyProductDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially_product
     *
     * @mbggenerated
     */
    int insert(TStoragePartiallyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially_product
     *
     * @mbggenerated
     */
    int insertSelective(TStoragePartiallyProduct record);
}