package com.coms.warehouse.dao.manage;

import com.coms.warehouse.beans.manage.TStoragePartially;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TStoragePartiallyDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    int insert(TStoragePartially record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    int insertSelective(TStoragePartially record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    TStoragePartially selectByPrimaryKey(Integer mateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TStoragePartially record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_storage_partially
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TStoragePartially record);
}